version: '3'

services:

  app:
    build: .
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
      - 8000:8000
    privileged: true # used for perf tests
    volumes:
      - .:/code

  grafana:
    depends_on:
      - prometheus
    env_file:
      - ./dashboards/grafana/env_vars
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    depends_on:
      - alertmanager
      - cadvisor
      - node-exporter
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./dashboards/prometheus:/etc/prometheus

  alertmanager:
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes: 
      - ./dashboards/alertmanager:/etc/alertmanager

  cadvisor:
    expose:
      - 8080
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  node-exporter:
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sysfs'
      - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    expose:
      - 9100
    image: prom/node-exporter
    volumes: 
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
